services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: wp
    volumes:
      - db_data:/var/lib/postgresql/data

  wordpress:
    build: .
    ports:
      - "8081:80"
    environment:
      # Le pasamos la URL de conexión que tu wp-config.php ya interpreta
      DATABASE_URL: postgres://user:pass@db:5432/wp
    depends_on:
      - db
    volumes:
      # Persistimos el directorio de uploads para que no se pierdan los archivos al redeploy
      - wp_uploads:/var/www/html/wp-content/uploads

volumes:
  db_data:
  wp_uploads:

